services:
  - type: worker
    name: tea-lead-finder
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SCAN_INTERVAL_MIN
        value: "360"
